package com.github.starnowski.jamolingo.core.operators.filter

import com.github.starnowski.jamolingo.common.json.JSONOverrideHelper
import com.github.starnowski.jamolingo.core.AbstractSpecification
import com.github.starnowski.jamolingo.core.context.DefaultEdmMongoContextFacade
import com.github.starnowski.jamolingo.core.context.EntityPropertiesMongoPathContextBuilder
import com.github.starnowski.jamolingo.core.mapping.EntityMapping
import com.github.starnowski.jamolingo.core.mapping.ODataMongoMappingFactory
import com.mongodb.MongoClientSettings
import org.apache.olingo.commons.api.edm.Edm
import org.apache.olingo.server.api.OData
import org.apache.olingo.server.api.uri.UriInfo
import org.apache.olingo.server.core.uri.parser.Parser
import org.bson.Document
import org.bson.UuidRepresentation
import org.bson.codecs.DocumentCodec
import org.bson.codecs.UuidCodecProvider
import org.bson.codecs.configuration.CodecRegistries
import org.bson.codecs.configuration.CodecRegistry
import org.bson.conversions.Bson
import org.bson.json.JsonWriterSettings
import spock.lang.Unroll

import java.nio.file.Files
import java.nio.file.Paths

class ODataFilterToMongoMatchParserWithOverrideConfigurationWrapperPropertyObjectTest extends AbstractSpecification {

    @Unroll
    def "should return expected stage bson objects"(){
        given:
            Bson expectedBson = Document.parse(bson)
            Edm edm = loadEmdProvider("edm/edm6_filter_main.xml")
            ODataMongoMappingFactory factory = new ODataMongoMappingFactory()
            def odataMapping = factory.build(edm.getSchema("MyService"))
            def entityMapping = odataMapping.getEntities().get("Example2")
            
            def helper = new JSONOverrideHelper()
            String mergePayload = Files.readString(Paths.get(getClass().getClassLoader().getResource("mappings/edm6_override_wrapper_object.json").toURI()))
            entityMapping = helper.applyChangesToJson(entityMapping, mergePayload, EntityMapping.class, JSONOverrideHelper.PatchType.MERGE)

            EntityPropertiesMongoPathContextBuilder entityPropertiesMongoPathContextBuilder = new EntityPropertiesMongoPathContextBuilder()
            def context = entityPropertiesMongoPathContextBuilder.build(entityMapping)
            def facade = DefaultEdmMongoContextFacade.builder()
                    .withEntityPropertiesMongoPathContext(context)
                    .build()

            JsonWriterSettings settings = JsonWriterSettings.builder().build()
            CodecRegistry registry = CodecRegistries.fromRegistries(
                    CodecRegistries.fromProviders(new UuidCodecProvider(UuidRepresentation.STANDARD)),
                    MongoClientSettings.getDefaultCodecRegistry()
            )
            DocumentCodec codec = new DocumentCodec(registry)

            UriInfo uriInfo = new Parser(edm, OData.newInstance())
                    .parseUri("examples2",
                            "\$filter=" +filter
                            , null, null)
            ODataFilterToMongoMatchParser tested = new ODataFilterToMongoMatchParser()

        when:
            def result = tested.parse(uriInfo.getFilterOption(), edm, facade)

        then:
            [((Document)result.getStageObjects().get(0)).toJson(settings, codec)] == [((Document)expectedBson).toJson(settings, codec)]

        where:
            [filter, bson] << oneToOneEdmPathsMappings()
    }

    @Unroll
    def "should return expected used MongoDB properties"(){
        given:
            Edm edm = loadEmdProvider("edm/edm6_filter_main.xml")
            ODataMongoMappingFactory factory = new ODataMongoMappingFactory()
            def odataMapping = factory.build(edm.getSchema("MyService"))
            def entityMapping = odataMapping.getEntities().get("Example2")
            
            def helper = new JSONOverrideHelper()
            String mergePayload = Files.readString(Paths.get(getClass().getClassLoader().getResource("mappings/edm6_override_wrapper_object.json").toURI()))
            entityMapping = helper.applyChangesToJson(entityMapping, mergePayload, EntityMapping.class, JSONOverrideHelper.PatchType.MERGE)

            EntityPropertiesMongoPathContextBuilder entityPropertiesMongoPathContextBuilder = new EntityPropertiesMongoPathContextBuilder()
            def context = entityPropertiesMongoPathContextBuilder.build(entityMapping)
            def facade = DefaultEdmMongoContextFacade.builder()
                    .withEntityPropertiesMongoPathContext(context)
                    .build()

            UriInfo uriInfo = new Parser(edm, OData.newInstance())
                    .parseUri("examples2",
                            "\$filter=" +filter
                            , null, null)
            ODataFilterToMongoMatchParser tested = new ODataFilterToMongoMatchParser()

        when:
            def result = tested.parse(uriInfo.getFilterOption(), edm, facade)

        then:
            new HashSet<>(result.getUsedMongoDocumentProperties()) == new HashSet(expectedFields as List)

        where:
            [filter, bson, expectedFields] << oneToOneEdmPathsMappings()
    }

    /**
     * Provides test data mapping OData filters to expected MongoDB $match documents and used properties.
     * Each test case uses the "renamed_" prefix for MongoDB properties.
     */
    static oneToOneEdmPathsMappings() {
        [
                [ "tags/all(t:t ne 'no such text' and t ne 'no such word')", """{"\$match": {"\$and": [{"\$and": [{"tags_wrapper.tags": {"\$not": {"\$elemMatch": {"\$not": {"\$ne": "no such text"}}}}}, {"tags_wrapper.tags": {"\$not": {"\$elemMatch": {"\$not": {"\$ne": "no such word"}}}}}]}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:startswith(t,'starlord') or t in ('star trek', 'star wars'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$or": [{"\$regexMatch": {"input": "\$\$t", "regex": "^\\\\Qstarlord\\\\E", "options": "i"}}, {"\$in": ["\$\$t", ["star trek", "star wars"]]}]}}}}, {"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:contains(t,'starlord') or contains(t,'trek') or contains(t,'wars'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$or": [{"\$or": [{"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qstarlord\\\\E", "options": "i"}}, {"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qtrek\\\\E", "options": "i"}}]}, {"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qwars\\\\E", "options": "i"}}]}}}}, {"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:contains(t,'starlord'))", """{"\$match": {"\$and": [{"tags_wrapper.tags": {"\$not": {"\$elemMatch": {"\$not": {"\$regex": "\\\\Qstarlord\\\\E"}}}}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:endswith(t,'web') or endswith(t,'trap'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$or": [{"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qweb\\\\E\$", "options": "i"}}, {"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qtrap\\\\E\$", "options": "i"}}]}}}}, {"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:length(t) eq 9)", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$eq": [{"\$strLenCP": "\$\$t"}, 9]}}}}, {"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:contains(tolower(t),'star'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$regexMatch": {"input": {"\$toLower": "\$\$t"}, "regex": "\\\\Qstar\\\\E", "options": "i"}}}}}, {"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:contains(tolower(t),tolower('star')))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$gte": [{"\$indexOfBytes": [{"\$toLower": "\$\$t"}, {"\$toLower": "star"}]}, 0]}}}}, {"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:startswith(toupper(t),toupper('star')))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$eq": [{"\$indexOfBytes": [{"\$toUpper": "\$\$t"}, {"\$toUpper": "star"}]}, 0]}}}}, {"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:endswith(tolower(t),tolower(t)))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$eq": [{"\$substrBytes": [{"\$toLower": "\$\$t"}, {"\$subtract": [{"\$strLenBytes": {"\$toLower": "\$\$t"}}, {"\$strLenBytes": {"\$toLower": "\$\$t"}}]}, {"\$strLenBytes": {"\$toLower": "\$\$t"}}]}, {"\$toLower": "\$\$t"}]}}}}, {"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:contains(toupper(t),'STAR'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$regexMatch": {"input": {"\$toUpper": "\$\$t"}, "regex": "\\\\QSTAR\\\\E", "options": "i"}}}}}, {"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}]}}]}}""", ["tags_wrapper.tags"]],
                [ "numericArray/all(n:n gt 5)", """{"\$match": {"\$and": [{"numericArray_wrapper.numericArray": {"\$not": {"\$elemMatch": {"\$not": {"\$gt": 5}}}}}]}}""", ["numericArray_wrapper.numericArray"]],
                [ "numericArray/all(n:n gt floor(5.05))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$numericArray_wrapper.numericArray", []]}, "as": "n", "cond": {"\$gt": ["\$\$n", {"\$floor": 5.05}]}}}}, {"\$size": {"\$ifNull": ["\$numericArray_wrapper.numericArray", []]}}]}}]}}""", ["numericArray_wrapper.numericArray"]],
                [ "numericArray/all(n:n add 2 gt round(n))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$numericArray_wrapper.numericArray", []]}, "as": "n", "cond": {"\$gt": [{"\$add": ["\$\$n", 2]}, {"\$round": "\$\$n"}]}}}}, {"\$size": {"\$ifNull": ["\$numericArray_wrapper.numericArray", []]}}]}}]}}""", ["numericArray_wrapper.numericArray"]],
                [ "numericArray/all(n:n eq 10 or n eq 20 or n eq 30)", """{"\$match":{"\$and":[{"\$expr":{"\$eq":[{"\$size":{"\$filter":{"input":{"\$ifNull":["\$numericArray_wrapper.numericArray",[]]},"as":"n","cond":{"\$or":[{"\$or":[{"\$eq":["\$\$n",10]},{"\$eq":["\$\$n",20]}]},{"\$eq":["\$\$n",30]}]}}}},{"\$size":{"\$ifNull":["\$numericArray_wrapper.numericArray",[]]}}]}}]}}""", ["numericArray_wrapper.numericArray"]],
                [ "complexList/all(c:c/someNumber gt 5)", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"someNumber_wrapper.someNumber": {"\$not": {"\$gt": 5}}}}}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/all(c:c/someNumber gt 25)", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"someNumber_wrapper.someNumber": {"\$not": {"\$gt": 25}}}}}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/all(c:c/someNumber lt 25)", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"someNumber_wrapper.someNumber": {"\$not": {"\$lt": 25}}}}}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/all(c:c/someNumber eq 10 or c/someNumber eq 20)", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$or": [{"\$eq": ["\$\$c.someNumber_wrapper.someNumber", 10]}, {"\$eq": ["\$\$c.someNumber_wrapper.someNumber", 20]}]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/all(c:c/someNumber add 5 gt 20)", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$add": ["\$\$c.someNumber_wrapper.someNumber", 5]}, 20]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/all(c:c/someNumber gt floor(5.05))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": ["\$\$c.someNumber_wrapper.someNumber", {"\$floor": 5.05}]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/all(c:c/someNumber add 2 gt round(c/someNumber))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$add": ["\$\$c.someNumber_wrapper.someNumber", 2]}, {"\$round": "\$\$c.someNumber_wrapper.someNumber"}]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/all(c:c/someNumber eq 20)", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"someNumber_wrapper.someNumber": {"\$not": {"\$eq": 20}}}}}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/all(c:startswith(c/someString,'Ap'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"someString_wrapper.someString": {"\$not": {"\$regex": "^\\\\QAp\\\\E"}}}}}}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "complexList/all(c:contains(c/someString,'ana'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"someString_wrapper.someString": {"\$not": {"\$regex": "\\\\Qana\\\\E"}}}}}}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "complexList/all(c:endswith(c/someString,'erry'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"someString_wrapper.someString": {"\$not": {"\$regex": "\\\\Qerry\\\\E\$"}}}}}}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'val1'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray_wrapper.nestedComplexArray": {"\$not": {"\$not": {"\$elemMatch": {"stringVal_wrapper.stringVal": {"\$not": {"\$eq": "val1"}}}}}}}}}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal"]],
                [ "complexList/all(c:c/nestedComplexArray/all(n:startswith(n/stringVal,'val')))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray_wrapper.nestedComplexArray": {"\$not": {"\$not": {"\$elemMatch": {"stringVal_wrapper.stringVal": {"\$not": {"\$regex": "^\\\\Qval\\\\E"}}}}}}}}}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal"]],
                [ "complexList/all(c:c/nestedComplexArray/all(n:contains(n/stringVal,'match')))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray_wrapper.nestedComplexArray": {"\$not": {"\$not": {"\$elemMatch": {"stringVal_wrapper.stringVal": {"\$not": {"\$regex": "\\\\Qmatch\\\\E"}}}}}}}}}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal"]],
                [ "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'val1' or n/stringVal eq 'test1'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}, "as": "n", "cond": {"\$or": [{"\$eq": ["\$\$n.stringVal_wrapper.stringVal", "val1"]}, {"\$eq": ["\$\$n.stringVal_wrapper.stringVal", "test1"]}]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal"]],
                [ "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'val1' or n/stringVal eq 'test1') and c/someNumber ge 20)", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$and": [{"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}, "as": "n", "cond": {"\$or": [{"\$eq": ["\$\$n.stringVal_wrapper.stringVal", "val1"]}, {"\$eq": ["\$\$n.stringVal_wrapper.stringVal", "test1"]}]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}]}, {"\$gte": ["\$\$c.someNumber_wrapper.someNumber", 20]}]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal", "complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'val1' or n/stringVal eq 'test1')) and complexList/any()", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}, "as": "n", "cond": {"\$or": [{"\$eq": ["\$\$n.stringVal_wrapper.stringVal", "val1"]}, {"\$eq": ["\$\$n.stringVal_wrapper.stringVal", "test1"]}]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}, 0]}}]}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal", "complexList_wrapper.complexList"]],
                [ "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'val1') and c/nestedComplexArray/any()) and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$and": [{"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$n.stringVal_wrapper.stringVal", "val1"]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}]}, {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}, 0]}]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal", "complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray"]],
                [ "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'matchAll'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray_wrapper.nestedComplexArray": {"\$not": {"\$not": {"\$elemMatch": {"stringVal_wrapper.stringVal": {"\$not": {"\$eq": "matchAll"}}}}}}}}}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal"]],
                [ "complexList/all(c:c/nestedComplexArray/all(n:n/numberVal gt 70))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray_wrapper.nestedComplexArray": {"\$not": {"\$not": {"\$elemMatch": {"numberVal_wrapper.numberVal": {"\$not": {"\$gt": 70}}}}}}}}}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.numberVal_wrapper.numberVal"]],
                [ "complexList/all(c:c/nestedComplexArray/any(n:n/numberVal eq 71) and c/nestedComplexArray/any(n:n/numberVal eq 72))", """{"\$match": {"\$and": [{"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray_wrapper.nestedComplexArray": {"\$not": {"\$elemMatch": {"numberVal_wrapper.numberVal": 71}}}}}}}, {"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray_wrapper.nestedComplexArray": {"\$not": {"\$elemMatch": {"numberVal_wrapper.numberVal": 72}}}}}}}]}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.numberVal_wrapper.numberVal"]],
                [ "complexList/all(c:c/nestedComplexArray/\$count ge 2)", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gte": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}, 2]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray"]],
                [ "complexList/all(c:c/nestedComplexArray/\$count ge 2)  and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gte": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}, 2]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray"]],
                [ "complexList/all(c:c/nestedComplexArray/any(n:n/numberVal ge 70 and n/stringVal eq 'matchAll')) and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray_wrapper.nestedComplexArray": {"\$not": {"\$elemMatch": {"numberVal_wrapper.numberVal": {"\$gte": 70}, "stringVal_wrapper.stringVal": "matchAll"}}}}}}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.numberVal_wrapper.numberVal", "complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal", "complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray"]],
                [ "complexList/all(c:c/primitiveStringList/all(n:startswith(n,'item1')))", """{"\$match":{"\$and":[{"complexList_wrapper.complexList":{"\$not":{"\$elemMatch":{"primitiveStringList_wrapper.primitiveStringList":{"\$not":{"\$not":{"\$elemMatch":{"\$not":{"\$regex":"^\\\\Qitem1\\\\E"}}}}}}}}}]}}""", ["complexList_wrapper.complexList.primitiveStringList_wrapper.primitiveStringList"]],
                [ "complexList/all(c:c/primitiveStringList/all(n:startswith(n,'item1'))) and complexList/any(c:c/primitiveStringList/any())", """{"\$match": {"\$and": [{"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"primitiveStringList_wrapper.primitiveStringList": {"\$not": {"\$not": {"\$elemMatch": {"\$not": {"\$regex": "^\\\\Qitem1\\\\E"}}}}}}}}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.primitiveStringList_wrapper.primitiveStringList", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList_wrapper.complexList.primitiveStringList_wrapper.primitiveStringList"]],
                [ "complexList/all(c:c/primitiveNumberList/all(n:n gt 10))", """{"\$match":{"\$and":[{"complexList_wrapper.complexList":{"\$not":{"\$elemMatch":{"primitiveNumberList_wrapper.primitiveNumberList":{"\$not":{"\$not":{"\$elemMatch":{"\$not":{"\$gt":10}}}}}}}}}]}}""", ["complexList_wrapper.complexList.primitiveNumberList_wrapper.primitiveNumberList"]],
                [ "complexList/all(c:c/primitiveNumberList/all(n:n gt 10)) and complexList/any(c:c/primitiveStringList/any())", """{"\$match": {"\$and": [{"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"primitiveNumberList_wrapper.primitiveNumberList": {"\$not": {"\$not": {"\$elemMatch": {"\$not": {"\$gt": 10}}}}}}}}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.primitiveStringList_wrapper.primitiveStringList", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList_wrapper.complexList.primitiveNumberList_wrapper.primitiveNumberList", "complexList_wrapper.complexList.primitiveStringList_wrapper.primitiveStringList"]],
                [ "complexList/all(c:c/nestedComplexArray/all(n:n/numberVal eq c/someNumber))  and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$n.numberVal_wrapper.numberVal", "\$\$c.someNumber_wrapper.someNumber"]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.numberVal_wrapper.numberVal", "complexList_wrapper.complexList.someNumber_wrapper.someNumber", "complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray"]],
                [ "complexList/all(c:c/nestedComplexArray/all(n:c/someNumber eq n/numberVal))  and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$c.someNumber_wrapper.someNumber", "\$\$n.numberVal_wrapper.numberVal"]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}]}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber", "complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.numberVal_wrapper.numberVal", "complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray"]],
                [ "complexList/all(c:not c/nestedComplexArray/all(n:c/someNumber eq n/numberVal))  and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$not": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$c.someNumber_wrapper.someNumber", "\$\$n.numberVal_wrapper.numberVal"]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}]}}}}}, {"\$size": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber", "complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.numberVal_wrapper.numberVal", "complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray"]],
                [ "tags/all(t:startswith(t,'star') and t ne 'starlord')", """{"\$match": {"\$and": [{"\$and": [{"tags_wrapper.tags": {"\$not": {"\$elemMatch": {"\$not": {"\$regex": "^\\\\Qstar\\\\E"}}}}}, {"tags_wrapper.tags": {"\$not": {"\$elemMatch": {"\$not": {"\$ne": "starlord"}}}}}]}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:startswith(t,'star') or t ne 'starlord')", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$or": [{"\$regexMatch": {"input": "\$\$t", "regex": "^\\\\Qstar\\\\E", "options": "i"}}, {"\$ne": ["\$\$t", "starlord"]}]}}}}, {"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/all(t:startswith(t,'star ') or t eq 'starlord')", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$or": [{"\$regexMatch": {"input": "\$\$t", "regex": "^\\\\Qstar \\\\E", "options": "i"}}, {"\$eq": ["\$\$t", "starlord"]}]}}}}, {"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}]}}]}}""", ["tags_wrapper.tags"]],
                [ "complexList/all(c:contains(c/someString,'e'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"someString_wrapper.someString": {"\$not": {"\$regex": "\\\\Qe\\\\E"}}}}}}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "complexList/all(c:c/someString eq 'Application')", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$not": {"\$elemMatch": {"someString_wrapper.someString": {"\$not": {"\$eq": "Application"}}}}}}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "complexList/any(c:c/nestedComplexArray/any(n:n/stringVal eq 'val1'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"nestedComplexArray_wrapper.nestedComplexArray": {"\$elemMatch": {"stringVal_wrapper.stringVal": "val1"}}}}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal"]],
                [ "complexList/any(c:c/nestedComplexArray/any(n:startswith(n/stringVal,'val')))", """{"\$match":{"\$and":[{"complexList_wrapper.complexList":{"\$elemMatch":{"nestedComplexArray_wrapper.nestedComplexArray":{"\$elemMatch":{"stringVal_wrapper.stringVal":{"\$regex":"^\\\\Qval\\\\E"}}}}}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal"]],
                [ "complexList/any(c:c/nestedComplexArray/any(n:contains(n/stringVal,'match')))", """{"\$match":{"\$and":[{"complexList_wrapper.complexList":{"\$elemMatch":{"nestedComplexArray_wrapper.nestedComplexArray":{"\$elemMatch":{"stringVal_wrapper.stringVal":{"\$regex":"\\\\Qmatch\\\\E"}}}}}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal"]],
                [ "complexList/any(c:c/nestedComplexArray/any(n:n/stringVal eq 'val1' or n/stringVal eq 'test1'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"\$or": [{"nestedComplexArray_wrapper.nestedComplexArray": {"\$elemMatch": {"stringVal_wrapper.stringVal": "val1"}}}, {"nestedComplexArray_wrapper.nestedComplexArray": {"\$elemMatch": {"stringVal_wrapper.stringVal": "test1"}}}]}}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal"]],
                [ "complexList/any(c:c/nestedComplexArray/any(n:n/stringVal eq 'val1' or n/stringVal eq 'test1') and c/someNumber ge 20)", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"\$or": [{"nestedComplexArray_wrapper.nestedComplexArray": {"\$elemMatch": {"stringVal_wrapper.stringVal": "val1"}}}, {"nestedComplexArray_wrapper.nestedComplexArray": {"\$elemMatch": {"stringVal_wrapper.stringVal": "test1"}}}], "someNumber_wrapper.someNumber": {"\$gte": 20}}}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.stringVal_wrapper.stringVal", "complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/any(c:c/nestedComplexArray/any(n:n/numberVal gt 70))", """{"\$match":{"\$and":[{"complexList_wrapper.complexList":{"\$elemMatch":{"nestedComplexArray_wrapper.nestedComplexArray":{"\$elemMatch":{"numberVal_wrapper.numberVal":{"\$gt":70}}}}}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.numberVal_wrapper.numberVal"]],
                [ "complexList/any(c:c/nestedComplexArray/any(n:n/numberVal eq 71) and c/nestedComplexArray/any(n:n/numberVal eq 72))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$and": [{"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$n.numberVal_wrapper.numberVal", 71]}}}}, 0]}, {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$n.numberVal_wrapper.numberVal", 72]}}}}, 0]}]}}}}, 0]}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray.numberVal_wrapper.numberVal"]],
                [ "complexList/any(c:c/nestedComplexArray/\$count ge 2)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gte": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray_wrapper.nestedComplexArray", []]}}, 2]}}}}, 0]}}]}}""", ["complexList_wrapper.complexList.nestedComplexArray_wrapper.nestedComplexArray"]],
                [ "complexList/any(c:c/primitiveStringList/any(n:startswith(n,'item11')))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"primitiveStringList_wrapper.primitiveStringList": {"\$elemMatch": {"\$regex": "^\\\\Qitem11\\\\E"}}}}}]}}""", ["complexList_wrapper.complexList.primitiveStringList_wrapper.primitiveStringList"]],
                [ "complexList/any(c:c/primitiveNumberList/any(n:n gt 10))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"primitiveNumberList_wrapper.primitiveNumberList": {"\$elemMatch": {"\$gt": 10}}}}}]}}""", ["complexList_wrapper.complexList.primitiveNumberList_wrapper.primitiveNumberList"]],
                [ "tags/any(t:t eq 'word wide web')", """{"\$match": {"\$and": [{"tags_wrapper.tags": {"\$elemMatch": {"\$eq": "word wide web"}}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'star'))", """{"\$match": {"\$and": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qstar\\\\E"}}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:contains(t,'spider'))", """{"\$match": {"\$and": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qspider\\\\E"}}}]}}""", ["tags_wrapper.tags"]],
                [ "numericArray/any(n:n gt 25)", """{"\$match": {"\$and": [{"numericArray_wrapper.numericArray": {"\$elemMatch": {"\$gt": 25}}}]}}""", ["numericArray_wrapper.numericArray"]],
                [ "numericArray/any(n:n lt 10)", """{"\$match": {"\$and": [{"numericArray_wrapper.numericArray": {"\$elemMatch": {"\$lt": 10}}}]}}""", ["numericArray_wrapper.numericArray"]],
                [ "tags/any(t:contains(tolower(t),'star'))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$regexMatch": {"input": {"\$toLower": "\$\$t"}, "regex": "\\\\Qstar\\\\E", "options": "i"}}}}}, 0]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:endswith(toupper(t),'TRAP'))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$regexMatch": {"input": {"\$toUpper": "\$\$t"}, "regex": "\\\\QTRAP\\\\E\$", "options": "i"}}}}}, 0]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:length(t) eq 8)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$eq": [{"\$strLenCP": "\$\$t"}, 8]}}}}, 0]}}]}}""", ["tags_wrapper.tags"]],
                [ "numericArray/any(n:n add 2 gt 100)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$numericArray_wrapper.numericArray", []]}, "as": "n", "cond": {"\$gt": [{"\$add": ["\$\$n", 2]}, 100]}}}}, 0]}}]}}""", ["numericArray_wrapper.numericArray"]],
                [ "tags/any(t:t ne 'no such text' and t ne 'no such word')", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$and": [{"\$ne": ["\$\$t", "no such text"]}, {"\$ne": ["\$\$t", "no such word"]}]}}}}, 0]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'star') and t ne 'starlord')", """{"\$match": {"\$and": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qstar\\\\E", "\$ne": "starlord"}}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'star') or t ne 'starlord')", """{"\$match": {"\$and": [{"\$or": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qstar\\\\E"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$ne": "starlord"}}}]}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'star ') or t eq 'starlord')", """{"\$match": {"\$and": [{"\$or": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qstar \\\\E"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$eq": "starlord"}}}]}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'starlord') or t in ('star trek', 'star wars'))", """{"\$match": {"\$and": [{"\$or": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qstarlord\\\\E"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$in": ["star trek", "star wars"]}}}]}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:contains(t,'starlord') or contains(t,'trek') or contains(t,'wars'))", """{"\$match": {"\$and": [{"\$or": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qstarlord\\\\E"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qtrek\\\\E"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qwars\\\\E"}}}]}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:contains(t,'starlord'))", """{"\$match": {"\$and": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qstarlord\\\\E"}}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:endswith(t,'web') or endswith(t,'trap'))", """{"\$match": {"\$and": [{"\$or": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qweb\\\\E\$"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qtrap\\\\E\$"}}}]}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:length(t) eq 9)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$eq": [{"\$strLenCP": "\$\$t"}, 9]}}}}, 0]}}]}}""", ["tags_wrapper.tags"]],
                [ "numericArray/any(n:n gt 5)", """{"\$match": {"\$and": [{"numericArray_wrapper.numericArray": {"\$elemMatch": {"\$gt": 5}}}]}}""", ["numericArray_wrapper.numericArray"]],
                [ "numericArray/any(n:n gt floor(5.05))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$numericArray_wrapper.numericArray", []]}, "as": "n", "cond": {"\$gt": ["\$\$n", {"\$floor": 5.05}]}}}}, 0]}}]}}""", ["numericArray_wrapper.numericArray"]],
                [ "numericArray/any(n:n add 2 gt round(n))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$numericArray_wrapper.numericArray", []]}, "as": "n", "cond": {"\$gt": [{"\$add": ["\$\$n", 2]}, {"\$round": "\$\$n"}]}}}}, 0]}}]}}""", ["numericArray_wrapper.numericArray"]],
                [ "numericArray/any(n:n eq 10 or n eq 20 or n eq 30)", """{"\$match": {"\$and": [{"\$or": [{"numericArray_wrapper.numericArray": {"\$elemMatch": {"\$eq": 10}}}, {"numericArray_wrapper.numericArray": {"\$elemMatch": {"\$eq": 20}}}, {"numericArray_wrapper.numericArray": {"\$elemMatch": {"\$eq": 30}}}]}]}}""", ["numericArray_wrapper.numericArray"]],
                [ "complexList/any(c:c/someNumber gt 5)", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someNumber_wrapper.someNumber": {"\$gt": 5}}}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/any(c:c/someNumber gt 25)", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someNumber_wrapper.someNumber": {"\$gt": 25}}}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/any(c:c/someNumber lt 25)", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someNumber_wrapper.someNumber": {"\$lt": 25}}}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/any(c:c/someNumber eq 10 or c/someNumber eq 20)", """{"\$match": {"\$and": [{"\$or": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someNumber_wrapper.someNumber": 10}}}, {"complexList_wrapper.complexList": {"\$elemMatch": {"someNumber_wrapper.someNumber": 20}}}]}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/any(c:c/someNumber add 5 gt 20)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$add": ["\$\$c.someNumber_wrapper.someNumber", 5]}, 20]}}}}, 0]}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/any(c:c/someNumber gt floor(5.05))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": ["\$\$c.someNumber_wrapper.someNumber", {"\$floor": 5.05}]}}}}, 0]}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/any(c:c/someNumber add 2 gt round(c/someNumber))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList_wrapper.complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$add": ["\$\$c.someNumber_wrapper.someNumber", 2]}, {"\$round": "\$\$c.someNumber_wrapper.someNumber"}]}}}}, 0]}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/any(c:c/someNumber eq 20)", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someNumber_wrapper.someNumber": 20}}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/any(c:c/someString eq 'Apple')", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someString_wrapper.someString": "Apple"}}}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "complexList/any(c:c/someNumber gt 35)", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someNumber_wrapper.someNumber": {"\$gt": 35}}}}]}}""", ["complexList_wrapper.complexList.someNumber_wrapper.someNumber"]],
                [ "complexList/any(c:c/someString eq 'Banana' or c/someString eq 'Cherry')", """{"\$match": {"\$and": [{"\$or": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someString_wrapper.someString": "Banana"}}}, {"complexList_wrapper.complexList": {"\$elemMatch": {"someString_wrapper.someString": "Cherry"}}}]}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "complexList/any(c:startswith(c/someString,'Ap'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someString_wrapper.someString": {"\$regex": "^\\\\QAp\\\\E"}}}}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "complexList/any(c:contains(c/someString,'ana'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someString_wrapper.someString": {"\$regex": "\\\\Qana\\\\E"}}}}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "complexList/any(c:endswith(c/someString,'erry'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someString_wrapper.someString": {"\$regex": "\\\\Qerry\\\\E\$"}}}}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "complexList/any(c:contains(c/someString,'e'))", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someString_wrapper.someString": {"\$regex": "\\\\Qe\\\\E"}}}}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "complexList/any(c:c/someString eq 'Application')", """{"\$match": {"\$and": [{"complexList_wrapper.complexList": {"\$elemMatch": {"someString_wrapper.someString": "Application"}}}]}}""", ["complexList_wrapper.complexList.someString_wrapper.someString"]],
                [ "nestedObject/tokens/any(t:t ne 'no such text')", """{"\$match": {"\$and": [{"nestedObject_wrapper.nestedObject.tokens_wrapper.tokens": {"\$elemMatch": {"\$ne": "no such text"}}}]}}""", ["nestedObject_wrapper.nestedObject.tokens_wrapper.tokens"]],
                [ "nestedObject/tokens/any(t:t eq 'first example') and nestedObject/numbers/any(t:t gt 5 and t lt 27)", """{"\$match": {"\$and": [{"\$and": [{"nestedObject_wrapper.nestedObject.tokens_wrapper.tokens": {"\$elemMatch": {"\$eq": "first example"}}}, {"nestedObject_wrapper.nestedObject.numbers_wrapper.numbers": {"\$elemMatch": {"\$gt": 5, "\$lt": 27}}}]}]}}""", ["nestedObject_wrapper.nestedObject.tokens_wrapper.tokens", "nestedObject_wrapper.nestedObject.numbers_wrapper.numbers"]],
                [ "uuidProp eq b921f1dd-3cbc-0495-fdab-8cd14d33f0aa", """{"\$match": {"\$and": [{"uuidProp_wrapper.uuidProp": {"\$binary": {"base64": "uSHx3Ty8BJX9q4zRTTPwqg==", "subType": "04"}}}]}}""", ["uuidProp_wrapper.uuidProp"]],
                [ "trim('   Poem   ') eq 'Poem'", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$trim": {"input": "   Poem   "}}, "Poem"]}}]}}""", []],
                [ "year(birthDate) eq 2024", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$year": "\$birthDate_wrapper.birthDate"}, 2024]}}]}}""", ["birthDate_wrapper.birthDate"]],
                [ "month(birthDate) eq 6", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$month": "\$birthDate_wrapper.birthDate"}, 6]}}]}}""", ["birthDate_wrapper.birthDate"]],
                [ "day(birthDate) eq 18", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$dayOfMonth": "\$birthDate_wrapper.birthDate"}, 18]}}]}}""", ["birthDate_wrapper.birthDate"]],
                [ "hour(timestamp) eq 10", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$hour": "\$timestamp_wrapper.timestamp"}, 10]}}]}}""", ["timestamp_wrapper.timestamp"]],
                [ "minute(timestamp) eq 15", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$minute": "\$timestamp_wrapper.timestamp"}, 15]}}]}}""", ["timestamp_wrapper.timestamp"]],
                [ "second(timestamp) eq 26", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$second": "\$timestamp_wrapper.timestamp"}, 26]}}]}}""", ["timestamp_wrapper.timestamp"]],
                [ "ceiling(floatValue) eq 1", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$ceil": "\$floatValue_wrapper.floatValue"}, 1]}}]}}""", ["floatValue_wrapper.floatValue"]],
                [ "floor(floatValue) eq 0", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$floor": "\$floatValue_wrapper.floatValue"}, 0]}}]}}""", ["floatValue_wrapper.floatValue"]],
                [ "round(floatValue) eq 1", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$round": "\$floatValue_wrapper.floatValue"}, 1]}}]}}""", ["floatValue_wrapper.floatValue"]],
                [ "tags/any(t:startswith(t,'spider') and t ne 'spiderweb' or startswith(t,'spider') and t ne 'spider' or contains(t,'wide') and t ne 'word wide')", """{"\$match": {"\$and": [{"\$or": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spiderweb"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spider"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qwide\\\\E", "\$ne": "word wide"}}}]}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'spider') and t ne 'spiderweb' or endswith(t,'web') and t ne 'spiderwebgg' or contains(t,'wide') and t ne 'word wide')", """{"\$match": {"\$and": [{"\$or": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spiderweb"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qweb\\\\E\$", "\$ne": "spiderwebgg"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qwide\\\\E", "\$ne": "word wide"}}}]}]}}""", ["tags_wrapper.tags"]],
                [ "tags/\$count ge 2", """{"\$match": {"\$and": [{"\$expr": {"\$gte": [{"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}, 2]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/\$count ge 3", """{"\$match": {"\$and": [{"\$expr": {"\$gte": [{"\$size": {"\$ifNull": ["\$tags_wrapper.tags", []]}}, 3]}}]}}""", ["tags_wrapper.tags"]],
                [ "plainString eq 'eOMtThyhVNLWUZNRcBaQKxI'", """{"\$match": {"\$and": [{"plainString_wrapper.plainString": "eOMtThyhVNLWUZNRcBaQKxI"}]}}""", ["plainString_wrapper.plainString"]],
                [ "tolower(plainString) eq 'eomtthyhvnlwuznrcbaqkxi'", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$toLower": "\$plainString_wrapper.plainString"}, "eomtthyhvnlwuznrcbaqkxi"]}}]}}""", ["plainString_wrapper.plainString"]],
                [ "tolower(plainString) eq tolower('eOMtThyhVNLWUZNRcBaQKxI')", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$toLower": "\$plainString_wrapper.plainString"}, {"\$toLower": "eOMtThyhVNLWUZNRcBaQKxI"}]}}]}}""", ["plainString_wrapper.plainString"]],
                [ "toupper(plainString) eq 'EOMTTHYHVNLWUZNRCBAQKXI'", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$toUpper": "\$plainString_wrapper.plainString"}, "EOMTTHYHVNLWUZNRCBAQKXI"]}}]}}""", ["plainString_wrapper.plainString"]],
                [ "plainString eq 'Some text'", """{"\$match": {"\$and": [{"plainString_wrapper.plainString": "Some text"}]}}""", ["plainString_wrapper.plainString"]],
                [ "plainString in ('Some text', 'no such text')", """{"\$match": {"\$and": [{"plainString_wrapper.plainString": {"\$in": ["Some text", "no such text"]}}]}}""", ["plainString_wrapper.plainString"]],
                [ "startswith(plainString,'So')", """{"\$match": {"\$and": [{"plainString_wrapper.plainString": {"\$regex": "^\\\\QSo\\\\E"}}]}}""", ["plainString_wrapper.plainString"]],
                [ "startswith(plainString,'So') and plainString eq 'Some text'", """{"\$match": {"\$and": [{"\$and": [{"plainString_wrapper.plainString": {"\$regex": "^\\\\QSo\\\\E"}}, {"plainString_wrapper.plainString": "Some text"}]}]}}""", ["plainString_wrapper.plainString"]],
                [ "startswith(plainString,'Some t') and smallInteger eq -1188957731", """{"\$match": {"\$and": [{"\$and": [{"plainString_wrapper.plainString": {"\$regex": "^\\\\QSome t\\\\E"}}, {"smallInteger_wrapper.smallInteger": -1188957731}]}]}}""", ["plainString_wrapper.plainString", "smallInteger_wrapper.smallInteger"]],
                [ "startswith(plainString,'Po') or smallInteger eq -113", """{"\$match": {"\$and": [{"\$or": [{"plainString_wrapper.plainString": {"\$regex": "^\\\\QPo\\\\E"}}, {"smallInteger_wrapper.smallInteger": -113}]}]}}""", ["plainString_wrapper.plainString", "smallInteger_wrapper.smallInteger"]],
                [ "timestamp ge 2024-07-20T10:00:00.00Z and timestamp le 2024-07-20T20:00:00.00Z", """{"\$match": {"\$and": [{"\$and": [{"timestamp_wrapper.timestamp": {"\$gte": {"\$date": "2024-07-20T10:00:00Z"}}}, {"timestamp_wrapper.timestamp": {"\$lte": {"\$date": "2024-07-20T20:00:00Z"}}}]}]}}""", ["timestamp_wrapper.timestamp"]],
                [ "plainString eq 'eOMtThyhVNLWUZNRcBaQKxI' and uuidProp eq b921f1dd-3cbc-0495-fdab-8cd14d33f0aa", """{"\$match": {"\$and": [{"\$and": [{"plainString_wrapper.plainString": "eOMtThyhVNLWUZNRcBaQKxI"}, {"uuidProp_wrapper.uuidProp": {"\$binary": {"base64": "uSHx3Ty8BJX9q4zRTTPwqg==", "subType": "04"}}}]}]}}""", ["plainString_wrapper.plainString", "uuidProp_wrapper.uuidProp"]],
                [ "plainString eq 'eOMtThyhVNLWUZNRcBaQKxI' and password eq 'password1'", """{"\$match": {"\$and": [{"\$and": [{"plainString_wrapper.plainString": "eOMtThyhVNLWUZNRcBaQKxI"}, {"password_wrapper.password": "password1"}]}]}}""", ["plainString_wrapper.plainString", "password_wrapper.password"]],
                [ "plainString eq 'eOMtThyhVNLWUZNRcBaQKxI' or password eq 'password1'", """{"\$match": {"\$and": [{"\$or": [{"plainString_wrapper.plainString": "eOMtThyhVNLWUZNRcBaQKxI"}, {"password_wrapper.password": "password1"}]}]}}""", ["plainString_wrapper.plainString", "password_wrapper.password"]],
                [ "tags/any(t:t eq 'developer') or tags/any(t:t eq 'LLM')", """{"\$match": {"\$and": [{"\$or": [{"tags_wrapper.tags": {"\$elemMatch": {"\$eq": "developer"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$eq": "LLM"}}}]}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:t in ('developer', 'LLM'))", """{"\$match": {"\$and": [{"tags_wrapper.tags": {"\$elemMatch": {"\$in": ["developer", "LLM"]}}}]}}""", ["tags_wrapper.tags"]],
                [ "length(plainString) eq 4", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$strLenCP": "\$plainString_wrapper.plainString"}, 4]}}]}}""", ["plainString_wrapper.plainString"]],
                [ "tags/any(t:startswith(t,'dev'))", """{"\$match": {"\$and": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qdev\\\\E"}}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'dev') and length(t) eq 9)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$and": [{"\$regexMatch": {"input": "\$\$t", "regex": "^\\\\Qdev\\\\E", "options": "i"}}, {"\$eq": [{"\$strLenCP": "\$\$t"}, 9]}]}}}}, 0]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:length(t) eq 13)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$eq": [{"\$strLenCP": "\$\$t"}, 13]}}}}, 0]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:tolower(t) eq 'developer')", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$eq": [{"\$toLower": "\$\$t"}, "developer"]}}}}, 0]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'spider') and endswith(t, 'web'))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags_wrapper.tags", []]}, "as": "t", "cond": {"\$and": [{"\$regexMatch": {"input": "\$\$t", "regex": "^\\\\Qspider\\\\E", "options": "i"}}, {"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qweb\\\\E\$", "options": "i"}}]}}}}, 0]}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'spider') and t eq 'spiderweb')", """{"\$match": {"\$and": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$eq": "spiderweb"}}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'spider') and t ne 'spiderweb')", """{"\$match": {"\$and": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spiderweb"}}}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'spider') and t ne 'spiderweb' or endswith(t,'web') and t ne 'spiderweb')", """{"\$match": {"\$and": [{"\$or": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spiderweb"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qweb\\\\E\$", "\$ne": "spiderweb"}}}]}]}}""", ["tags_wrapper.tags"]],
                [ "tags/any(t:startswith(t,'spider') and t ne 'spiderweb' or endswith(t,'web') and t ne 'spiderweb' or contains(t,'wide') and t ne 'word wide')", """{"\$match": {"\$and": [{"\$or": [{"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spiderweb"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qweb\\\\E\$", "\$ne": "spiderweb"}}}, {"tags_wrapper.tags": {"\$elemMatch": {"\$regex": "\\\\Qwide\\\\E", "\$ne": "word wide"}}}]}]}}""", ["tags_wrapper.tags"]]
        ]
    }
}
