package com.github.starnowski.jamolingo.core.operators.filter

import com.github.starnowski.jamolingo.core.AbstractSpecification
import com.mongodb.MongoClientSettings
import org.apache.olingo.commons.api.edm.Edm
import org.apache.olingo.server.api.OData
import org.apache.olingo.server.api.uri.UriInfo
import org.apache.olingo.server.core.uri.parser.Parser
import org.bson.Document
import org.bson.UuidRepresentation
import org.bson.codecs.DocumentCodec
import org.bson.codecs.UuidCodecProvider
import org.bson.codecs.configuration.CodecRegistries
import org.bson.codecs.configuration.CodecRegistry
import org.bson.conversions.Bson
import org.bson.json.JsonWriterSettings
import spock.lang.Unroll

class ODataFilterToMongoMatchParserTest extends AbstractSpecification {

    @Unroll
    def "should return expected stage bson objects"(){
        given:
        System.out.println("Testing filter: " + filter)
        Bson expectedBson = Document.parse(bson)
        Edm edm = loadEmdProvider(edmConfigFile)
        JsonWriterSettings settings = JsonWriterSettings.builder().build()
        CodecRegistry registry = CodecRegistries.fromRegistries(
                CodecRegistries.fromProviders(new UuidCodecProvider(UuidRepresentation.STANDARD)),
                MongoClientSettings.getDefaultCodecRegistry()
        )
        DocumentCodec codec = new DocumentCodec(registry)

        UriInfo uriInfo = new Parser(edm, OData.newInstance())
                .parseUri(path,
                        "\$filter=" +filter
                        , null, null)
        ODataFilterToMongoMatchParser tested = new ODataFilterToMongoMatchParser()

        when:
        def result = tested.parse(uriInfo.getFilterOption(), edm)

        then:
        [((Document)result.getStageObjects().get(0)).toJson(settings, codec)] == [((Document)expectedBson).toJson(settings, codec)]
        result.getSelectedFields() == expectedFields as Set

        where:
        [edmConfigFile, path , filter, bson, expectedFields] << oneToOneEdmPathsMappings()
    }

    static oneToOneEdmPathsMappings() {
        [
                ["edm/edm6_filter_main.xml", "examples2"  , "tags/all(t:t ne 'no such text' and t ne 'no such word')", """{"\$match": {"\$and": [{"\$and": [{"tags": {"\$not": {"\$elemMatch": {"\$not": {"\$ne": "no such text"}}}}}, {"tags": {"\$not": {"\$elemMatch": {"\$not": {"\$ne": "no such word"}}}}}]}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/all(t:startswith(t,'starlord') or t in ('star trek', 'star wars'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$or": [{"\$regexMatch": {"input": "\$\$t", "regex": "^\\\\Qstarlord\\\\E", "options": "i"}}, {"\$in": ["\$\$t", ["star trek", "star wars"]]}]}}}}, {"\$size": {"\$ifNull": ["\$tags", []]}}]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/all(t:contains(t,'starlord') or contains(t,'trek') or contains(t,'wars'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$or": [{"\$or": [{"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qstarlord\\\\E", "options": "i"}}, {"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qtrek\\\\E", "options": "i"}}]}, {"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qwars\\\\E", "options": "i"}}]}}}}, {"\$size": {"\$ifNull": ["\$tags", []]}}]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/all(t:contains(t,'starlord'))", """{"\$match": {"\$and": [{"tags": {"\$not": {"\$elemMatch": {"\$not": {"\$regex": "\\\\Qstarlord\\\\E"}}}}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/all(t:endswith(t,'web') or endswith(t,'trap'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$or": [{"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qweb\\\\E\$", "options": "i"}}, {"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qtrap\\\\E\$", "options": "i"}}]}}}}, {"\$size": {"\$ifNull": ["\$tags", []]}}]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/all(t:length(t) eq 9)", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$eq": [{"\$strLenCP": "\$\$t"}, 9]}}}}, {"\$size": {"\$ifNull": ["\$tags", []]}}]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/all(t:contains(tolower(t),'star'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$regexMatch": {"input": {"\$toLower": "\$\$t"}, "regex": "\\\\Qstar\\\\E", "options": "i"}}}}}, {"\$size": {"\$ifNull": ["\$tags", []]}}]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/all(t:contains(tolower(t),tolower('star')))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$gte": [{"\$indexOfBytes": [{"\$toLower": "\$\$t"}, {"\$toLower": "star"}]}, 0]}}}}, {"\$size": {"\$ifNull": ["\$tags", []]}}]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/all(t:startswith(toupper(t),toupper('star')))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$eq": [{"\$indexOfBytes": [{"\$toUpper": "\$\$t"}, {"\$toUpper": "star"}]}, 0]}}}}, {"\$size": {"\$ifNull": ["\$tags", []]}}]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/all(t:endswith(tolower(t),tolower(t)))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$eq": [{"\$substrBytes": [{"\$toLower": "\$\$t"}, {"\$subtract": [{"\$strLenBytes": {"\$toLower": "\$\$t"}}, {"\$strLenBytes": {"\$toLower": "\$\$t"}}]}, {"\$strLenBytes": {"\$toLower": "\$\$t"}}]}, {"\$toLower": "\$\$t"}]}}}}, {"\$size": {"\$ifNull": ["\$tags", []]}}]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/all(t:contains(toupper(t),'STAR'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$regexMatch": {"input": {"\$toUpper": "\$\$t"}, "regex": "\\\\QSTAR\\\\E", "options": "i"}}}}}, {"\$size": {"\$ifNull": ["\$tags", []]}}]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "numericArray/all(n:n gt 5)", """{"\$match": {"\$and": [{"numericArray": {"\$not": {"\$elemMatch": {"\$not": {"\$gt": 5}}}}}]}}""", ["numericArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "numericArray/all(n:n gt floor(5.05))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$numericArray", []]}, "as": "n", "cond": {"\$gt": ["\$\$n", {"\$floor": 5.05}]}}}}, {"\$size": {"\$ifNull": ["\$numericArray", []]}}]}}]}}""", ["numericArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "numericArray/all(n:n add 2 gt round(n))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$numericArray", []]}, "as": "n", "cond": {"\$gt": [{"\$add": ["\$\$n", 2]}, {"\$round": "\$\$n"}]}}}}, {"\$size": {"\$ifNull": ["\$numericArray", []]}}]}}]}}""", ["numericArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "numericArray/all(n:n eq 10 or n eq 20 or n eq 30)", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$numericArray", []]}, "as": "n", "cond": {"\$or": [{"\$or": [{"\$eq": ["\$\$n", 10]}, {"\$eq": ["\$\$n", 20]}]}, {"\$eq": ["\$\$n", 30]}]}}}}, {"\$size": {"\$ifNull": ["\$numericArray", []]}}]}}]}}""", ["numericArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:c/someNumber gt 5)", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"someNumber": {"\$not": {"\$gt": 5}}}}}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:c/someNumber gt 25)", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"someNumber": {"\$not": {"\$gt": 25}}}}}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:c/someNumber lt 25)", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"someNumber": {"\$not": {"\$lt": 25}}}}}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:c/someNumber eq 10 or c/someNumber eq 20)", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$or": [{"\$eq": ["\$\$c.someNumber", 10]}, {"\$eq": ["\$\$c.someNumber", 20]}]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:c/someNumber add 5 gt 20)", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$add": ["\$\$c.someNumber", 5]}, 20]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:c/someNumber gt floor(5.05))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": ["\$\$c.someNumber", {"\$floor": 5.05}]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:c/someNumber add 2 gt round(c/someNumber))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$add": ["\$\$c.someNumber", 2]}, {"\$round": "\$\$c.someNumber"}]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:c/someNumber eq 20)", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"someNumber": {"\$not": {"\$eq": 20}}}}}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:startswith(c/someString,'Ap'))", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"someString": {"\$not": {"\$regex": "^\\\\QAp\\\\E"}}}}}}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:contains(c/someString,'ana'))", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"someString": {"\$not": {"\$regex": "\\\\Qana\\\\E"}}}}}}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:endswith(c/someString,'erry'))", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"someString": {"\$not": {"\$regex": "\\\\Qerry\\\\E\$"}}}}}}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'val1'))", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray": {"\$not": {"\$not": {"\$elemMatch": {"stringVal": {"\$not": {"\$eq": "val1"}}}}}}}}}}]}}""", ["complexList.nestedComplexArray.stringVal"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/all(n:startswith(n/stringVal,'val')))", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray": {"\$not": {"\$not": {"\$elemMatch": {"stringVal": {"\$not": {"\$regex": "^\\\\Qval\\\\E"}}}}}}}}}}]}}""", ["complexList.nestedComplexArray.stringVal"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/all(n:contains(n/stringVal,'match')))", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray": {"\$not": {"\$not": {"\$elemMatch": {"stringVal": {"\$not": {"\$regex": "\\\\Qmatch\\\\E"}}}}}}}}}}]}}""", ["complexList.nestedComplexArray.stringVal"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'val1' or n/stringVal eq 'test1'))", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}, "as": "n", "cond": {"\$or": [{"\$eq": ["\$\$n.stringVal", "val1"]}, {"\$eq": ["\$\$n.stringVal", "test1"]}]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}]}}""", ["complexList.nestedComplexArray.stringVal"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'val1' or n/stringVal eq 'test1') and c/someNumber ge 20)", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$and": [{"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}, "as": "n", "cond": {"\$or": [{"\$eq": ["\$\$n.stringVal", "val1"]}, {"\$eq": ["\$\$n.stringVal", "test1"]}]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}]}, {"\$gte": ["\$\$c.someNumber", 20]}]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}]}}""", ["complexList.nestedComplexArray.stringVal", "complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'val1' or n/stringVal eq 'test1')) and complexList/any()", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}, "as": "n", "cond": {"\$or": [{"\$eq": ["\$\$n.stringVal", "val1"]}, {"\$eq": ["\$\$n.stringVal", "test1"]}]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$ifNull": ["\$complexList", []]}}, 0]}}]}]}}""", ["complexList.nestedComplexArray.stringVal", "complexList"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'val1') and c/nestedComplexArray/any()) and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$and": [{"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$n.stringVal", "val1"]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}]}, {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$n.stringVal", "val1"]}}}}, 0]}]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList.nestedComplexArray.stringVal", "complexList.nestedComplexArray"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/all(n:n/stringVal eq 'matchAll'))", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray": {"\$not": {"\$not": {"\$elemMatch": {"stringVal": {"\$not": {"\$eq": "matchAll"}}}}}}}}}}]}}""", ["complexList.nestedComplexArray.stringVal"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/all(n:n/numberVal gt 70))", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray": {"\$not": {"\$not": {"\$elemMatch": {"numberVal": {"\$not": {"\$gt": 70}}}}}}}}}}]}}""", ["complexList.nestedComplexArray.numberVal"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/any(n:n/numberVal eq 71) and c/nestedComplexArray/any(n:n/numberVal eq 72))", """{"\$match": {"\$and": [{"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray": {"\$not": {"\$elemMatch": {"numberVal": 71}}}}}}}, {"complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray": {"\$not": {"\$elemMatch": {"numberVal": 72}}}}}}}]}]}}""", ["complexList.nestedComplexArray.numberVal"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/\$count ge 2)", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gte": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}, 2]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}]}}""", ["complexList.nestedComplexArray"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/\$count ge 2)  and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gte": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}, 2]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList.nestedComplexArray"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/any(n:n/numberVal ge 70 and n/stringVal eq 'matchAll')) and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"nestedComplexArray": {"\$not": {"\$elemMatch": {"numberVal": {"\$gte": 70}, "stringVal": "matchAll"}}}}}}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList.nestedComplexArray.numberVal", "complexList.nestedComplexArray.stringVal", "complexList.nestedComplexArray"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/primitiveStringList/all(n:startswith(n,'item1')))", """{"\$match":{"\$and":[{"complexList":{"\$not":{"\$elemMatch":{"primitiveStringList":{"\$not":{"\$not":{"\$elemMatch":{"\$not":{"\$regex":"^\\\\Qitem1\\\\E"}}}}}}}}}]}}""", ["complexList.primitiveStringList"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/primitiveStringList/all(n:startswith(n,'item1'))) and complexList/any(c:c/primitiveStringList/any())", """{"\$match": {"\$and": [{"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"primitiveStringList": {"\$not": {"\$not": {"\$elemMatch": {"\$not": {"\$regex": "^\\\\Qitem1\\\\E"}}}}}}}}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.primitiveStringList", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList.primitiveStringList"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/primitiveNumberList/all(n:n gt 10))", """{"\$match":{"\$and":[{"complexList":{"\$not":{"\$elemMatch":{"primitiveNumberList":{"\$not":{"\$not":{"\$elemMatch":{"\$not":{"\$gt":10}}}}}}}}}]}}""", ["complexList.primitiveNumberList"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/primitiveNumberList/all(n:n gt 10)) and complexList/any(c:c/primitiveStringList/any())", """{"\$match": {"\$and": [{"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"primitiveNumberList": {"\$not": {"\$not": {"\$elemMatch": {"\$not": {"\$gt": 10}}}}}}}}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.primitiveStringList", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList.primitiveNumberList", "complexList.primitiveStringList"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/all(n:n/numberVal eq c/someNumber))  and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$n.numberVal", "\$\$c.someNumber"]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList.nestedComplexArray.numberVal", "complexList.someNumber", "complexList.nestedComplexArray"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:c/nestedComplexArray/all(n:c/someNumber eq n/numberVal))  and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$c.someNumber", "\$\$n.numberVal"]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}]}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList.someNumber", "complexList.nestedComplexArray.numberVal", "complexList.nestedComplexArray"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "complexList/all(c:not c/nestedComplexArray/all(n:c/someNumber eq n/numberVal))  and complexList/any(c:c/nestedComplexArray/any())", """{"\$match": {"\$and": [{"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$not": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$c.someNumber", "\$\$n.numberVal"]}}}}, {"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}]}}}}}, {"\$size": {"\$ifNull": ["\$complexList", []]}}]}}, {"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}, 0]}}}}, 0]}}]}]}}""", ["complexList.someNumber", "complexList.nestedComplexArray.numberVal", "complexList.nestedComplexArray"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "tags/all(t:startswith(t,'star') and t ne 'starlord')", """{"\$match": {"\$and": [{"\$and": [{"tags": {"\$not": {"\$elemMatch": {"\$not": {"\$regex": "^\\\\Qstar\\\\E"}}}}}, {"tags": {"\$not": {"\$elemMatch": {"\$not": {"\$ne": "starlord"}}}}}]}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "tags/all(t:startswith(t,'star') or t ne 'starlord')", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$or": [{"\$regexMatch": {"input": "\$\$t", "regex": "^\\\\Qstar\\\\E", "options": "i"}}, {"\$ne": ["\$\$t", "starlord"]}]}}}}, {"\$size": {"\$ifNull": ["\$tags", []]}}]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2"  , "tags/all(t:startswith(t,'star ') or t eq 'starlord')", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$or": [{"\$regexMatch": {"input": "\$\$t", "regex": "^\\\\Qstar \\\\E", "options": "i"}}, {"\$eq": ["\$\$t", "starlord"]}]}}}}, {"\$size": {"\$ifNull": ["\$tags", []]}}]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:contains(c/someString,'e'))", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"someString": {"\$not": {"\$regex": "\\\\Qe\\\\E"}}}}}}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/all(c:c/someString eq 'Application')", """{"\$match": {"\$and": [{"complexList": {"\$not": {"\$elemMatch": {"someString": {"\$not": {"\$eq": "Application"}}}}}}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/nestedComplexArray/any(n:n/stringVal eq 'val1'))", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"nestedComplexArray": {"\$elemMatch": {"stringVal": "val1"}}}}}]}}""", ["complexList.nestedComplexArray.stringVal"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/nestedComplexArray/any(n:startswith(n/stringVal,'val')))", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"nestedComplexArray": {"\$elemMatch": {"stringVal": {"\$regex": "^\\\\Qval\\\\E"}}}}}}]}}""", ["complexList.nestedComplexArray.stringVal"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/nestedComplexArray/any(n:contains(n/stringVal,'match')))", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"nestedComplexArray": {"\$elemMatch": {"stringVal": {"\$regex": "\\\\Qmatch\\\\E"}}}}}}]}}""", ["complexList.nestedComplexArray.stringVal"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/nestedComplexArray/any(n:n/stringVal eq 'val1' or n/stringVal eq 'test1'))", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"\$or": [{"nestedComplexArray": {"\$elemMatch": {"stringVal": "val1"}}}, {"nestedComplexArray": {"\$elemMatch": {"stringVal": "test1"}}}]}}}]}}""", ["complexList.nestedComplexArray.stringVal"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/nestedComplexArray/any(n:n/stringVal eq 'val1' or n/stringVal eq 'test1') and c/someNumber ge 20)", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"\$or": [{"nestedComplexArray": {"\$elemMatch": {"stringVal": "val1"}}}, {"nestedComplexArray": {"\$elemMatch": {"stringVal": "test1"}}}], "someNumber": {"\$gte": 20}}}}]}}""", ["complexList.nestedComplexArray.stringVal", "complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/nestedComplexArray/any(n:n/numberVal gt 70))", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"nestedComplexArray": {"\$elemMatch": {"numberVal": {"\$gt": 70}}}}}}]}}""", ["complexList.nestedComplexArray.numberVal"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/nestedComplexArray/any(n:n/numberVal eq 71) and c/nestedComplexArray/any(n:n/numberVal eq 72))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$and": [{"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$n.numberVal", 71]}}}}, 0]}, {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}, "as": "n", "cond": {"\$eq": ["\$\$n.numberVal", 72]}}}}, 0]}]}}}}, 0]}}]}}""", ["complexList.nestedComplexArray.numberVal"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/nestedComplexArray/\$count ge 2)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gte": [{"\$size": {"\$ifNull": ["\$\$c.nestedComplexArray", []]}}, 2]}}}}, 0]}}]}}""", ["complexList.nestedComplexArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/primitiveStringList/any(n:startswith(n,'item11')))", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"primitiveStringList": {"\$elemMatch": {"\$regex": "^\\\\Qitem11\\\\E"}}}}}]}}""", ["complexList.primitiveStringList"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/primitiveNumberList/any(n:n gt 10))", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"primitiveNumberList": {"\$elemMatch": {"\$gt": 10}}}}}]}}""", ["complexList.primitiveNumberList"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:t eq 'word wide web')", """{"\$match": {"\$and": [{"tags": {"\$elemMatch": {"\$eq": "word wide web"}}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'star'))", """{"\$match": {"\$and": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qstar\\\\E"}}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:contains(t,'spider'))", """{"\$match": {"\$and": [{"tags": {"\$elemMatch": {"\$regex": "\\\\Qspider\\\\E"}}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "numericArray/any(n:n gt 25)", """{"\$match": {"\$and": [{"numericArray": {"\$elemMatch": {"\$gt": 25}}}]}}""", ["numericArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "numericArray/any(n:n lt 10)", """{"\$match": {"\$and": [{"numericArray": {"\$elemMatch": {"\$lt": 10}}}]}}""", ["numericArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:contains(tolower(t),'star'))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$regexMatch": {"input": {"\$toLower": "\$\$t"}, "regex": "\\\\Qstar\\\\E", "options": "i"}}}}}, 0]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:endswith(toupper(t),'TRAP'))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$regexMatch": {"input": {"\$toUpper": "\$\$t"}, "regex": "\\\\QTRAP\\\\E\$", "options": "i"}}}}}, 0]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:length(t) eq 8)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$eq": [{"\$strLenCP": "\$\$t"}, 8]}}}}, 0]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "numericArray/any(n:n add 2 gt 100)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$numericArray", []]}, "as": "n", "cond": {"\$gt": [{"\$add": ["\$\$n", 2]}, 100]}}}}, 0]}}]}}""", ["numericArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:t ne 'no such text' and t ne 'no such word')", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$and": [{"\$ne": ["\$\$t", "no such text"]}, {"\$ne": ["\$\$t", "no such word"]}]}}}}, 0]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'star') and t ne 'starlord')", """{"\$match": {"\$and": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qstar\\\\E", "\$ne": "starlord"}}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'star') or t ne 'starlord')", """{"\$match": {"\$and": [{"\$or": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qstar\\\\E"}}}, {"tags": {"\$elemMatch": {"\$ne": "starlord"}}}]}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'star ') or t eq 'starlord')", """{"\$match": {"\$and": [{"\$or": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qstar \\\\E"}}}, {"tags": {"\$elemMatch": {"\$eq": "starlord"}}}]}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'starlord') or t in ('star trek', 'star wars'))", """{"\$match": {"\$and": [{"\$or": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qstarlord\\\\E"}}}, {"tags": {"\$elemMatch": {"\$in": ["star trek", "star wars"]}}}]}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:contains(t,'starlord') or contains(t,'trek') or contains(t,'wars'))", """{"\$match": {"\$and": [{"\$or": [{"tags": {"\$elemMatch": {"\$regex": "\\\\Qstarlord\\\\E"}}}, {"tags": {"\$elemMatch": {"\$regex": "\\\\Qtrek\\\\E"}}}, {"tags": {"\$elemMatch": {"\$regex": "\\\\Qwars\\\\E"}}}]}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:contains(t,'starlord'))", """{"\$match": {"\$and": [{"tags": {"\$elemMatch": {"\$regex": "\\\\Qstarlord\\\\E"}}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:endswith(t,'web') or endswith(t,'trap'))", """{"\$match": {"\$and": [{"\$or": [{"tags": {"\$elemMatch": {"\$regex": "\\\\Qweb\\\\E\$"}}}, {"tags": {"\$elemMatch": {"\$regex": "\\\\Qtrap\\\\E\$"}}}]}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:length(t) eq 9)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$eq": [{"\$strLenCP": "\$\$t"}, 9]}}}}, 0]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "numericArray/any(n:n gt 5)", """{"\$match": {"\$and": [{"numericArray": {"\$elemMatch": {"\$gt": 5}}}]}}""", ["numericArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "numericArray/any(n:n gt floor(5.05))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$numericArray", []]}, "as": "n", "cond": {"\$gt": ["\$\$n", {"\$floor": 5.05}]}}}}, 0]}}]}}""", ["numericArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "numericArray/any(n:n add 2 gt round(n))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$numericArray", []]}, "as": "n", "cond": {"\$gt": [{"\$add": ["\$\$n", 2]}, {"\$round": "\$\$n"}]}}}}, 0]}}]}}""", ["numericArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "numericArray/any(n:n eq 10 or n eq 20 or n eq 30)", """{"\$match": {"\$and": [{"\$or": [{"numericArray": {"\$elemMatch": {"\$eq": 10}}}, {"numericArray": {"\$elemMatch": {"\$eq": 20}}}, {"numericArray": {"\$elemMatch": {"\$eq": 30}}}]}]}}""", ["numericArray"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someNumber gt 5)", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"someNumber": {"\$gt": 5}}}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someNumber gt 25)", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"someNumber": {"\$gt": 25}}}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someNumber lt 25)", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"someNumber": {"\$lt": 25}}}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someNumber eq 10 or c/someNumber eq 20)", """{"\$match": {"\$and": [{"\$or": [{"complexList": {"\$elemMatch": {"someNumber": 10}}}, {"complexList": {"\$elemMatch": {"someNumber": 20}}}]}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someNumber add 5 gt 20)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$add": ["\$\$c.someNumber", 5]}, 20]}}}}, 0]}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someNumber gt floor(5.05))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": ["\$\$c.someNumber", {"\$floor": 5.05}]}}}}, 0]}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someNumber add 2 gt round(c/someNumber))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$complexList", []]}, "as": "c", "cond": {"\$gt": [{"\$add": ["\$\$c.someNumber", 2]}, {"\$round": "\$\$c.someNumber"}]}}}}, 0]}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someNumber eq 20)", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"someNumber": 20}}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someString eq 'Apple')", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"someString": "Apple"}}}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someNumber gt 35)", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"someNumber": {"\$gt": 35}}}}]}}""", ["complexList.someNumber"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someString eq 'Banana' or c/someString eq 'Cherry')", """{"\$match": {"\$and": [{"\$or": [{"complexList": {"\$elemMatch": {"someString": "Banana"}}}, {"complexList": {"\$elemMatch": {"someString": "Cherry"}}}]}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:startswith(c/someString,'Ap'))", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"someString": {"\$regex": "^\\\\QAp\\\\E"}}}}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:contains(c/someString,'ana'))", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"someString": {"\$regex": "\\\\Qana\\\\E"}}}}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:endswith(c/someString,'erry'))", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"someString": {"\$regex": "\\\\Qerry\\\\E\$"}}}}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:contains(c/someString,'e'))", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"someString": {"\$regex": "\\\\Qe\\\\E"}}}}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2", "complexList/any(c:c/someString eq 'Application')", """{"\$match": {"\$and": [{"complexList": {"\$elemMatch": {"someString": "Application"}}}]}}""", ["complexList.someString"]],
                ["edm/edm6_filter_main.xml", "examples2", "nestedObject/tokens/any(t:t ne 'no such text')", """{"\$match": {"\$and": [{"nestedObject.tokens": {"\$elemMatch": {"\$ne": "no such text"}}}]}}""", ["nestedObject.tokens"]],
                ["edm/edm6_filter_main.xml", "examples2", "nestedObject/tokens/any(t:t eq 'first example') and nestedObject/numbers/any(t:t gt 5 and t lt 27)", """{"\$match": {"\$and": [{"\$and": [{"nestedObject.tokens": {"\$elemMatch": {"\$eq": "first example"}}}, {"nestedObject.numbers": {"\$elemMatch": {"\$gt": 5, "\$lt": 27}}}]}]}}""", ["nestedObject.tokens", "nestedObject.numbers"]],
                ["edm/edm6_filter_main.xml", "examples2", "uuidProp eq b921f1dd-3cbc-0495-fdab-8cd14d33f0aa", """{"\$match": {"\$and": [{"uuidProp": {"\$binary": {"base64": "uSHx3Ty8BJX9q4zRTTPwqg==", "subType": "04"}}}]}}""", ["uuidProp"]],
                ["edm/edm6_filter_main.xml", "examples2", "trim('   Poem   ') eq 'Poem'", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$trim": {"input": "   Poem   "}}, "Poem"]}}]}}""", []],
                ["edm/edm6_filter_main.xml", "examples2", "year(birthDate) eq 2024", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$year": "\$birthDate"}, 2024]}}]}}""", ["birthDate"]],
                ["edm/edm6_filter_main.xml", "examples2", "month(birthDate) eq 6", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$month": "\$birthDate"}, 6]}}]}}""", ["birthDate"]],
                ["edm/edm6_filter_main.xml", "examples2", "day(birthDate) eq 18", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$dayOfMonth": "\$birthDate"}, 18]}}]}}""", ["birthDate"]],
                ["edm/edm6_filter_main.xml", "examples2", "hour(timestamp) eq 10", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$hour": "\$timestamp"}, 10]}}]}}""", ["timestamp"]],
                ["edm/edm6_filter_main.xml", "examples2", "minute(timestamp) eq 15", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$minute": "\$timestamp"}, 15]}}]}}""", ["timestamp"]],
                ["edm/edm6_filter_main.xml", "examples2", "second(timestamp) eq 26", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$second": "\$timestamp"}, 26]}}]}}""", ["timestamp"]],
                ["edm/edm6_filter_main.xml", "examples2", "ceiling(floatValue) eq 1", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$ceil": "\$floatValue"}, 1]}}]}}""", ["floatValue"]],
                ["edm/edm6_filter_main.xml", "examples2", "floor(floatValue) eq 0", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$floor": "\$floatValue"}, 0]}}]}}""", ["floatValue"]],
                ["edm/edm6_filter_main.xml", "examples2", "round(floatValue) eq 1", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$round": "\$floatValue"}, 1]}}]}}""", ["floatValue"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'spider') and t ne 'spiderweb' or startswith(t,'spider') and t ne 'spider' or contains(t,'wide') and t ne 'word wide')", """{"\$match": {"\$and": [{"\$or": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spiderweb"}}}, {"tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spider"}}}, {"tags": {"\$elemMatch": {"\$regex": "\\\\Qwide\\\\E", "\$ne": "word wide"}}}]}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'spider') and t ne 'spiderweb' or endswith(t,'web') and t ne 'spiderwebgg' or contains(t,'wide') and t ne 'word wide')", """{"\$match": {"\$and": [{"\$or": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spiderweb"}}}, {"tags": {"\$elemMatch": {"\$regex": "\\\\Qweb\\\\E\$", "\$ne": "spiderwebgg"}}}, {"tags": {"\$elemMatch": {"\$regex": "\\\\Qwide\\\\E", "\$ne": "word wide"}}}]}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/\$count ge 2", """{"\$match": {"\$and": [{"\$expr": {"\$gte": [{"\$size": {"\$ifNull": ["\$tags", []]}}, 2]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/\$count ge 3", """{"\$match": {"\$and": [{"\$expr": {"\$gte": [{"\$size": {"\$ifNull": ["\$tags", []]}}, 3]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "plainString eq 'eOMtThyhVNLWUZNRcBaQKxI'", """{"\$match": {"\$and": [{"plainString": "eOMtThyhVNLWUZNRcBaQKxI"}]}}""", ["plainString"]],
                ["edm/edm6_filter_main.xml", "examples2", "tolower(plainString) eq 'eomtthyhvnlwuznrcbaqkxi'", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$toLower": "\$plainString"}, "eomtthyhvnlwuznrcbaqkxi"]}}]}}""", ["plainString"]],
                ["edm/edm6_filter_main.xml", "examples2", "tolower(plainString) eq tolower('eOMtThyhVNLWUZNRcBaQKxI')", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$toLower": "\$plainString"}, {"\$toLower": "eOMtThyhVNLWUZNRcBaQKxI"}]}}]}}""", ["plainString"]],
                ["edm/edm6_filter_main.xml", "examples2", "toupper(plainString) eq 'EOMTTHYHVNLWUZNRCBAQKXI'", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$toUpper": "\$plainString"}, "EOMTTHYHVNLWUZNRCBAQKXI"]}}]}}""", ["plainString"]],
                ["edm/edm6_filter_main.xml", "examples2", "plainString eq 'Some text'", """{"\$match": {"\$and": [{"plainString": "Some text"}]}}""", ["plainString"]],
                ["edm/edm6_filter_main.xml", "examples2", "plainString in ('Some text', 'no such text')", """{"\$match": {"\$and": [{"plainString": {"\$in": ["Some text", "no such text"]}}]}}""", ["plainString"]],
                ["edm/edm6_filter_main.xml", "examples2", "startswith(plainString,'So')", """{"\$match": {"\$and": [{"plainString": {"\$regex": "^\\\\QSo\\\\E"}}]}}""", ["plainString"]],
                ["edm/edm6_filter_main.xml", "examples2", "startswith(plainString,'So') and plainString eq 'Some text'", """{"\$match": {"\$and": [{"\$and": [{"plainString": {"\$regex": "^\\\\QSo\\\\E"}}, {"plainString": "Some text"}]}]}}""", ["plainString"]],
                ["edm/edm6_filter_main.xml", "examples2", "startswith(plainString,'Some t') and smallInteger eq -1188957731", """{"\$match": {"\$and": [{"\$and": [{"plainString": {"\$regex": "^\\\\QSome t\\\\E"}}, {"smallInteger": -1188957731}]}]}}""", ["plainString", "smallInteger"]],
                ["edm/edm6_filter_main.xml", "examples2", "startswith(plainString,'Po') or smallInteger eq -113", """{"\$match": {"\$and": [{"\$or": [{"plainString": {"\$regex": "^\\\\QPo\\\\E"}}, {"smallInteger": -113}]}]}}""", ["plainString", "smallInteger"]],
                ["edm/edm6_filter_main.xml", "examples2", "timestamp ge 2024-07-20T10:00:00.00Z and timestamp le 2024-07-20T20:00:00.00Z", """{"\$match": {"\$and": [{"\$and": [{"timestamp": {"\$gte": {"\$date": "2024-07-20T10:00:00Z"}}}, {"timestamp": {"\$lte": {"\$date": "2024-07-20T20:00:00Z"}}}]}]}}""", ["timestamp"]],
                ["edm/edm6_filter_main.xml", "examples2", "plainString eq 'eOMtThyhVNLWUZNRcBaQKxI' and uuidProp eq b921f1dd-3cbc-0495-fdab-8cd14d33f0aa", """{"\$match": {"\$and": [{"\$and": [{"plainString": "eOMtThyhVNLWUZNRcBaQKxI"}, {"uuidProp": {"\$binary": {"base64": "uSHx3Ty8BJX9q4zRTTPwqg==", "subType": "04"}}}]}]}}""", ["plainString", "uuidProp"]],
                ["edm/edm6_filter_main.xml", "examples2", "plainString eq 'eOMtThyhVNLWUZNRcBaQKxI' and password eq 'password1'", """{"\$match": {"\$and": [{"\$and": [{"plainString": "eOMtThyhVNLWUZNRcBaQKxI"}, {"password": "password1"}]}]}}""", ["plainString", "password"]],
                ["edm/edm6_filter_main.xml", "examples2", "plainString eq 'eOMtThyhVNLWUZNRcBaQKxI' or password eq 'password1'", """{"\$match": {"\$and": [{"\$or": [{"plainString": "eOMtThyhVNLWUZNRcBaQKxI"}, {"password": "password1"}]}]}}""", ["plainString", "password"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:t eq 'developer') or tags/any(t:t eq 'LLM')", """{"\$match": {"\$and": [{"\$or": [{"tags": {"\$elemMatch": {"\$eq": "developer"}}}, {"tags": {"\$elemMatch": {"\$eq": "LLM"}}}]}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:t in ('developer', 'LLM'))", """{"\$match": {"\$and": [{"tags": {"\$elemMatch": {"\$in": ["developer", "LLM"]}}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tolower(plainString) eq 'poem'", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$toLower": "\$plainString"}, "poem"]}}]}}""", ["plainString"]],
                ["edm/edm6_filter_main.xml", "examples2", "toupper(plainString) eq 'POEM'", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$toUpper": "\$plainString"}, "POEM"]}}]}}""", ["plainString"]],
                ["edm/edm6_filter_main.xml", "examples2", "length(plainString) eq 4", """{"\$match": {"\$and": [{"\$expr": {"\$eq": [{"\$strLenCP": "\$plainString"}, 4]}}]}}""", ["plainString"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'dev'))", """{"\$match": {"\$and": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qdev\\\\E"}}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'dev') and length(t) eq 9)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$and": [{"\$regexMatch": {"input": "\$\$t", "regex": "^\\\\Qdev\\\\E", "options": "i"}}, {"\$eq": [{"\$strLenCP": "\$\$t"}, 9]}]}}}}, 0]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:length(t) eq 13)", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$eq": [{"\$strLenCP": "\$\$t"}, 13]}}}}, 0]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:tolower(t) eq 'developer')", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$eq": [{"\$toLower": "\$\$t"}, "developer"]}}}}, 0]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'spider') and endswith(t, 'web'))", """{"\$match": {"\$and": [{"\$expr": {"\$gt": [{"\$size": {"\$filter": {"input": {"\$ifNull": ["\$tags", []]}, "as": "t", "cond": {"\$and": [{"\$regexMatch": {"input": "\$\$t", "regex": "^\\\\Qspider\\\\E", "options": "i"}}, {"\$regexMatch": {"input": "\$\$t", "regex": "\\\\Qweb\\\\E\$", "options": "i"}}]}}}}, 0]}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'spider') and t eq 'spiderweb')", """{"\$match": {"\$and": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$eq": "spiderweb"}}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'spider') and t ne 'spiderweb')", """{"\$match": {"\$and": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spiderweb"}}}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'spider') and t ne 'spiderweb' or endswith(t,'web') and t ne 'spiderweb')", """{"\$match": {"\$and": [{"\$or": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spiderweb"}}}, {"tags": {"\$elemMatch": {"\$regex": "\\\\Qweb\\\\E\$", "\$ne": "spiderweb"}}}]}]}}""", ["tags"]],
                ["edm/edm6_filter_main.xml", "examples2", "tags/any(t:startswith(t,'spider') and t ne 'spiderweb' or endswith(t,'web') and t ne 'spiderweb' or contains(t,'wide') and t ne 'word wide')", """{"\$match": {"\$and": [{"\$or": [{"tags": {"\$elemMatch": {"\$regex": "^\\\\Qspider\\\\E", "\$ne": "spiderweb"}}}, {"tags": {"\$elemMatch": {"\$regex": "\\\\Qweb\\\\E\$", "\$ne": "spiderweb"}}}, {"tags": {"\$elemMatch": {"\$regex": "\\\\Qwide\\\\E", "\$ne": "word wide"}}}]}]}}""", ["tags"]]
        ]
    }
}
