spring.data.mongodb.database=demos
spring.data.mongodb.uri=mongodb://localhost:27017/demos
# Liquibase configuration
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
