package com.github.starnowski.jamolingo.select;

import java.util.List;
import org.bson.conversions.Bson;

public interface OlingoOperatorResult {

  /** Aggregation pipeline stages generated by this operator. */
  List<Bson> getStageObjects();

  /** MongoDB document properties (dot notation) read by this operator. */
  List<String> getUsedMongoDocumentProperties();

  /**
   * MongoDB document properties (dot notation) that are written (added or overwritten) by this
   * operator.
   */
  List<String> getWrittenMongoDocumentProperties();

  /** MongoDB document properties (dot notation) that are newly added by this operator. */
  List<String> getAddedMongoDocumentProperties();

  /** MongoDB document properties (dot notation) that are explicitly removed by this operator. */
  List<String> getRemovedMongoDocumentProperties();

  /**
   * Indicates whether this operator redefines the document shape, meaning the output no longer
   * represents the original entity.
   */
  boolean isDocumentShapeRedefined();
}
