package com.github.starnowski.jamolingo.select;

import java.util.List;
import org.bson.conversions.Bson;

/**
 * Represents the result of an OData operator processing, providing information about MongoDB
 * aggregation stages and affected fields.
 */
public interface OlingoOperatorResult {

  /**
   * Aggregation pipeline stages generated by this operator.
   *
   * @return list of Bson objects representing the stages
   */
  List<Bson> getStageObjects();

  /**
   * MongoDB document properties (dot notation) read by this operator.
   *
   * @return list of used property paths
   */
  List<String> getUsedMongoDocumentProperties();

  /**
   * MongoDB document properties (dot notation) that are written (added or overwritten) by this
   * operator.
   *
   * @return list of written property paths
   */
  List<String> getWrittenMongoDocumentProperties();

  /**
   * MongoDB document properties (dot notation) that are newly added by this operator.
   *
   * @return list of added property paths
   */
  List<String> getAddedMongoDocumentProperties();

  /**
   * MongoDB document properties (dot notation) that are explicitly removed by this operator.
   *
   * @return list of removed property paths
   */
  List<String> getRemovedMongoDocumentProperties();

  /**
   * Indicates whether this operator redefines the document shape, meaning the output no longer
   * represents the original entity.
   *
   * @return true if the document shape is redefined, false otherwise
   */
  boolean isDocumentShapeRedefined();
}
