# MongoDB configuration
# Quarkus will use Dev Services by default if no connection string is provided, 
# but for tests we rely on the junit5-mongo-extension-quarkus which clears/loads data.
# The connection string for the actual app (when running in dev mode or prod)
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=demos
